name: CI/CD Pipeline

on:
  push:
    branches:
      - worked

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория в CI/CD
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Проверка кода
      - name: Echo Test
        run: echo "Running basic tests!"

      # Шаг 3: Сборка Docker образа (локальная проверка)
      - name: Build Docker image
        run: docker compose up -d --build

      # Шаг 4: Проверка доступности базы данных
      - name: Wait for database to be ready
        run: |
          until curl --silent --fail db:5432; do
            echo "Waiting for database to be ready..."
            sleep 2
          done
          echo "Database is ready!"

      # Шаг 5: Подождать, пока API будет готово
      - name: Wait for the API to be ready
        run: sleep 10

      # Шаг 6: Проверка доступности API
      - name: Ping API
        run: |
          curl --fail http://127.0.0.1:6007 || exit 1
