name: CI/CD Pipeline

on:
  push:
    branches:
      - worked2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория в CI/CD
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Сборка Docker образа (локальная проверка)
      - name: Build Docker image
        run: docker compose up -d --build
        
      - name: Wait for API run
        run: sleep 10

      - name: CreateTabe
        run: | 
         curl -X GET http://127.0.0.1:6007/createTable
         docker ps -a

      - name: Ping API
        run: |
          curl -X GET --fail http://127.0.0.1:6007 || exit 1
          docker ps -a

      - name: Send data
        run: curl --location 'http://127.0.0.1:6007' --form 'surname="Водопьяно"' --form 'name="Виктор"' --form 'patronymic="Анатольевич"' --form 'group="НМТ-413901"'

      - name: get students
        run: curl -X GET http://127.0.0.1:6007/getStudents